#! /bin/bash
#Launch an instance with port:9000 and n2-standard-1

# Update & Install "java11 & unzip" 
sudo apt update && sudo apt install openjdk-11-jdk unzip -y

# Home directory for sonar user
sudo mkdir -p /home/sonar

cd /opt/
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip
unzip sonarqube-9.6.1.59531.zip
sudo useradd --shell /bin/bash sonar
chown sonar:sonar /opt/sonarqube-9.6.1.59531 -R
chmod 777 /opt/sonarqube-9.6.1.59531 -R
su - sonar

#run this on server manually
#cd /opt/sonarqube-9.6.1.59531/bin/linux-x86-64/
#sh sonar.sh start
#sh sonar.sh status

#echo "user=admin & password=admin"
